#!/bin/bash
x="$(apt list)"
y="$( while IFS= read -r line ; do line=${line%%/*} ; echo "$line" ; done <<< "$x" )"
z="$(apt-cache depends $y | grep -w Depends )"
r="$(echo -n "$z" | grep -c '^')"
echo "$r"
